### ISSUE TITLE
missing Terminal.h

### ISSUE THREAD

**Issue by johndpope** [neoneye/newton-commander#16]
I tried commenting this import statement  out

-(BOOL)openTerminalWithPath:(NSString_)aPath {
    @try {
    /_  TerminalApplication\* terminal = [SBApplication applicationWithBundleIdentifier:@"com.apple.Terminal"];
        [terminal activate];
        [terminal open:[NSArray arrayWithObject:aPath]];*/
        return YES;
    } @catch(id ue) {
        return NO;
    } @finally {
        return NO;
    }
}

but still seeing 

sdef: couldn't get sdef for /Users/Applications/Utilities/Terminal.app (error -43)
2014-08-24 13:26:05.563 defaults[65727:1200293] 
The domain/default pair of (/Users/Applications/Utilities/Terminal.app/Contents/Info, CFBundleIdentifier) does not exist
sdp: option `--bundleid' requires an argument
usage: sdp -f{ahmst} [-o directory | file | -] [options...] [file]
Command /bin/sh failed with exit code 2

Can you please commit Terminal.h?

**Comment by johndpope** [comment]
I will close this - I got it working by dragging and dropping the terminal app into Compile Sources.
This wasn't clear to me as it couldn't find my source and this missing Teminal.h file was a side effect. 

Thx 
JP

**Comment by neoneye** [comment]
Happy to hear you got it working.

How can I improve the build instructions?
