### ISSUE TITLE
Codesign the app and the worker 

### ISSUE THREAD

**Issue by neoneye** [neoneye/newton-commander#9]
The first time the app is started it is blocked by Mavericks and requires manually unblocking it. The user has to follow a procedure of 6 step in order to get it running.

Optimally would be just to:
1. download the zip
2. unzip
3. open and it's running

See [Distributing Applications Outside the Mac App Store](https://developer.apple.com/library/mac/documentation/IDEs/Conceptual/AppDistributionGuide/DistributingApplicationsOutside/DistributingApplicationsOutside.html#//apple_ref/doc/uid/TP40012582-CH12-SW2)

I think I'm going to need an installer, because NewtonCommander has a worker process.

**Comment by RoyiAvital** [comment]
Why does it ask for my Administrator password on launch?
Is it safe?

**Comment by neoneye** [comment]
RoyiAvital the worker runs as administrator. However it runs as the regular user most of the time. The user can choose to switch to another user via the top-left picker, so you can choose to run as root and peek into folder that one wouldn't normally have access to.
